spelling_fix_branch_name = 'spelling-fix'
commit_message = 'Spelling fix'
commit_email = 'ghspellcheckbot@gmail.com'
commit_name = 'Github Spellcheck Bot'
github_username = 'ghspellcheckbot'
fork_remote_name = 'spellfork'
pr_title = "Spelling fixes"
pr_message = "Spelling fixes generated by a bot"
